---
- name: Prepare nullmailer install
  when:
    - nullmailer_enabled
  tags:
    - nullmailer
  block:
    - name: Install required packages
      loop:
        - nullmailer
        - bsd-mailx
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      tags:
        - nullmailer

    - name: Write aliases config
      ansible.builtin.template:
        src: aliases.j2
        dest: /etc/aliases
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags:
        - nullmailer

    - name: Divert sendmail binary
      when:
        - nullmailer_sendmail_overwrite
      community.general.dpkg_divert:
        path: /usr/sbin/sendmail
        divert: /usr/sbin/sendmail-bin
        rename: true
      tags:
        - nullmailer

    - name: Overwrite sendmail command
      notify:
        - Restart nullmailer
      when:
        - nullmailer_sendmail_overwrite
      diff: false
      ansible.builtin.template:
        src: sendmail.j2
        dest: /usr/sbin/sendmail
        owner: root
        group: root
        mode: u=rwx,g=rw,o=rx
      tags:
        - nullmailer

    - name: Write adminaddr config
      notify:
        - Restart nullmailer
      ansible.builtin.template:
        src: adminaddr.j2
        dest: /etc/nullmailer/adminaddr
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Write defaultdomain config
      notify:
        - Restart nullmailer
      ansible.builtin.template:
        src: defaultdomain.j2
        dest: /etc/nullmailer/defaultdomain
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Write allmailfrom config
      notify:
        - Restart nullmailer
      ansible.builtin.template:
        src: allmailfrom.j2
        dest: /etc/nullmailer/allmailfrom
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Write remotes config
      notify:
        - Restart nullmailer
      ansible.builtin.template:
        src: remotes.j2
        dest: /etc/nullmailer/remotes
        mode: u=rw,g=,o=
        owner: mail
        group: mail
      tags:
        - nullmailer

    - name: Write me config
      notify:
        - Restart nullmailer
      when:
        - ansible_os_family | lower != "debian"
      ansible.builtin.template:
        src: me.j2
        dest: /etc/nullmailer/me
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Remove me config
      notify:
        - Restart nullmailer
      when:
        - ansible_os_family | lower == "debian"
      ansible.builtin.file:
        path: /etc/nullmailer/me
        state: absent
      tags:
        - nullmailer

    - name: Start nullmailer service
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.systemd:
        name: nullmailer
        state: started
        daemon_reload: true
        masked: false
        enabled: true
      tags:
        - nullmailer

- name: Purge nullmailer install
  when:
    - not nullmailer_enabled
  ansible.builtin.package:
    name: nullmailer
    purge: true
    state: absent
  tags:
    - nullmailer

- name: Revert sendmail divert
  when:
    - not nullmailer_enabled
  community.general.dpkg_divert:
    path: /usr/sbin/sendmail
    state: absent
    rename: true
    force: true
  tags:
    - nullmailer

...
